package server

import (
	"context"
	"path"
	"strings"

	. "github.com/dave/jennifer/jen"
)

func renderTransportEndpoints(info *GenerationInfo) (err error) {

	srcFile := NewFileProxy(info.PkgName)

	srcFile.PackageComment("GENERATED BY i2s. DO NOT EDIT.")

	ctx := prepareContext(info)
	ctx = context.WithValue(ctx, "code", srcFile)

	srcFile.ImportName(packagePathGoKitEndpoint, "endpoint")

	srcFile.Type().Id(endpointsSetName).StructFunc(func(g *Group) {

		for _, signature := range info.Iface.Methods {
			g.Id(endpointsStructFieldName(signature.Name)).Qual(packagePathGoKitEndpoint, "Endpoint")
		}

	}).Line()

	return srcFile.Save(path.Join(info.OutputFilePath, "transport", strings.ToLower(info.ServiceName), "endpoints.go"))
}

func endpointsStructFieldName(str string) string {
	return str + "Endpoint"
}

var ctx_contextContext = Id(_ctx_).Qual(packagePathContext, "Context")
